version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: food-delivery
    ports:
      - "6379:6379"
    command: redis-server --requirepass your_strong_password --appendonly yes
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
    driver: local